/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package hashTable;

import hashTable.base.HashTable;
import org.junit.jupiter.api.Test;

import java.util.Objects;

import static org.junit.jupiter.api.Assertions.*;

class LibraryTest {

  @Test
  public void hashTableTesting() {
    HashTable<String, String> hashTable = new HashTable<>();

    // Testing the item is added and retrieve the value
    hashTable.add("Osaid", "student");
    assertEquals("student", hashTable.get("Osaid"));

    // Testing the item is added and retrieve the value
    assertNull(hashTable.get("Blah"));

    // Testing Collisions adding and getting
    hashTable.add("Khaleel", "student");
    assertEquals("student", hashTable.get("Khaleel"));


  }

}
