/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package linked.list.challenges;

import java.util.EmptyStackException;

public class Library {
  public static void main(String[] args) throws Exception {

  }



}
