/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package hashTable;

import hashTable.base.HashTable;

import java.util.Objects;

public class Library {
  public static void main(String[] args) {


  }

}
