/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package graph;

import graph.base.Graph;

import java.util.ArrayList;
import java.util.List;

public class Library {
  public static void main(String[] args) {

  }
}
