/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package quickSort;

import org.junit.jupiter.api.Test;

import java.util.Arrays;

import static org.junit.jupiter.api.Assertions.*;

class LibraryTest {
  @Test
  void quickSortTesting() {
    int[] array = {8, 4, 23, 42, 16, 15};
    int[] arraySorted = {4, 8, 15, 16, 23, 42};

    int[] arrayEC1 = {};
    int[] arrayEC2 = {1};

    int[] arrayUnique = {5, 12, 7, 5, 5, 7};
    int[] arrayUniqueSorted = {5, 5, 5, 7, 7, 12};

    Library.QuickSort(array, 0, 5);
    assertEquals(Arrays.toString(arraySorted), Arrays.toString(array));

    Library.QuickSort(arrayEC1, 0, 0);
    Library.QuickSort(arrayEC2, 0, 0);
    assertEquals(Arrays.toString(arrayEC1), Arrays.toString(arrayEC1));
    assertEquals(Arrays.toString(arrayEC2), Arrays.toString(arrayEC2));

    Library.QuickSort(arrayUnique, 0, 5);
    assertEquals(Arrays.toString(arrayUniqueSorted), Arrays.toString(arrayUnique));
  }
}
