/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package trees.chaleenges;

import trees.chaleenges.base.BinarySearchTree;

public class Library {
  public static void main(String[] args) {
  }
}
