/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package trees.chaleenges;

import trees.chaleenges.base.BinarySearchTree;
import trees.chaleenges.base.BinaryTree;

public class Library {
  public static void main(String[] args) {



  }
}
