/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package InsertionSort;

public class Library {

  public int[] insertionSort(int[] array) {

    for (int i = 1; i < array.length; i++) {
      int j = i - 1;
      int temp = array[i];

      while (j >= 0 && temp < array[j]) {
        array[j + 1] = array[j];
        j = j - 1;
      }
      array[j + 1] = temp;
    }

    return array;
  }

  public boolean someLibraryMethod() {
    return true;
  }
}
