/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package InsertionSort;

import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;

import java.util.Arrays;

import static org.junit.jupiter.api.Assertions.*;

class LibraryTest {

  @DisplayName("this bad boy tests the insertion sorting")
  @Test
  void insertionSortingTest() {
    Library classUnderTest = new Library();
    int[] array = {8, 4, 23, 42, 16, 15};
    int[] arraySorted = {4, 8, 15, 16, 23, 42};
    assertEquals(Arrays.toString(arraySorted), Arrays.toString(classUnderTest.insertionSort(array)));
  }
}
