/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package mergeSort;

import java.util.Arrays;

public class Library {

  public static void main(String[] args) {

  }

  public void mergeSort(int[] arr) {
    int n = arr.length;

    if (n > 1) {
      int mid = n / 2;

      int[] left = new int[mid];
      for (int i = 0; i < mid; i++) {
        left[i] = arr[i];
      }

      int[] right = new int[n-mid];
      for (int i = mid; i < n; i++) {
        right[i - mid] = arr[i];
      }

      mergeSort(left);
      mergeSort(right);

      merge(left, right, arr);
    }
  }

  public void merge(int[] left, int[] right, int[] arr) {
    int i = 0;
    int j = 0;
    int k = 0;

    while (i < left.length && j < right.length) {
      if (left[i] <= right[j]) {
        arr[k] = left[i];
        i++;
      } else {
        arr[k] = right[j];
        j++;
      }
      k++;
    }

    while (i < left.length) {
      arr[k] = left[i];
      i++;
      k++;
    }

    while (j < right.length) {
      arr[k] = right[j];
      j++;
      k++;
    }
  }

}
